
package carmax;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suraj
 */
public class buycars extends javax.swing.JFrame {
PreparedStatement pst=null;
Connection con=null;
String sql=null;
ResultSet rs=null;
    /**
     * Creates new form buycars
     */
    public buycars() {
        con=Javaconnect.ConnectrDb();
        initComponents();
        cameroinf(); 
        cmper();
        crz();
        crzper();
        mst();
        mstper();
    }
public void close(){
       WindowEvent  winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

private void cameroinf(){
        try{  
         sql="select CAR_MODEL,COMPANY,PRICE from CAR_INFO where SERIAL_NO=(select SERIAL_NO from CAR_PERFORMNCE where SERIAL_NO=90000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         cm.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
private void cmper(){
        try{
         sql="select TOP_SPEED,MILEAGE,SEATS from CAR_PERFORMNCE where SERIAL_NO=(select SERIAL_NO from CAR_INFO where SERIAL_NO=90000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         cmper.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
private void crz(){
        try{
         sql="select CAR_MODEL,COMPANY,PRICE from CAR_INFO where SERIAL_NO=(select SERIAL_NO from CAR_PERFORMNCE where SERIAL_NO=50000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         crz.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
private void crzper(){
        try{
         sql="select TOP_SPEED,MILEAGE,SEATS from CAR_PERFORMNCE where SERIAL_NO=(select SERIAL_NO from CAR_INFO where SERIAL_NO=50000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         crzper.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
private void mst(){
        try{
         sql="select CAR_MODEL,COMPANY,PRICE from CAR_INFO where SERIAL_NO=(select SERIAL_NO from CAR_PERFORMNCE where SERIAL_NO=60000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         mst.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
private void mstper(){
        try{
         sql="select TOP_SPEED,MILEAGE,SEATS from CAR_PERFORMNCE where SERIAL_NO=(select SERIAL_NO from CAR_INFO where SERIAL_NO=60000)";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         mstper.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        crzper = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        mstper = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        mst = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmper = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        cm = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        crz = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(980, 820));
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/chevrolet-cruze-photos.jpg"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 310, 280, 190);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/ford_mustang_2015-wallpaper-320x240.jpg"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 510, 280, 190);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/carmaxlogo.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 0, 240, 100);

        crzper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(crzper);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 420, 452, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Car Information");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 120, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Car Performance");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 200, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Car Information");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 310, 110, 17);

        mstper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(mstper);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(300, 630, 452, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Car Performance");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 400, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Car Information");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 510, 130, 17);

        mst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(mst);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(300, 530, 452, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Car Performance");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 600, 150, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/camero287x200.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 280, 180);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/bnw.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(760, 200, 160, 50);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/bnw.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(770, 390, 160, 50);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/bnw.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(770, 590, 160, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Want a Loan.. dont worry we also provide car loan with trusted banks");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 10, 630, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/aplynow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 50, 210, 50);

        cmper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(cmper);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(300, 220, 452, 60);

        cm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(cm);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(300, 140, 452, 60);

        crz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(crz);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(300, 330, 452, 60);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carmax/rsz_1home_button.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 50, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Chevrolet Camero will be delivered to your given address our near by showroom officers will contact you for direct payment");
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Chevrolet Cruze will be delivered to your given address our near by showroom officers will contact you for direct payment");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Ford mustang will be delivered to your given address our near by showroom officers will contact you for direct payment");
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        loan ln=new loan();
        
        ln.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
        Home hm=new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        close();
        Home hm=new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buycars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buycars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buycars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buycars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buycars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cm;
    private javax.swing.JTable cmper;
    private javax.swing.JTable crz;
    private javax.swing.JTable crzper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable mst;
    private javax.swing.JTable mstper;
    // End of variables declaration//GEN-END:variables
}
